########DIRECTORYS################
configdirectory: /var/lib/imap
partition-default: /var/spool/imap
sievedir: /var/lib/imap/sieve
#################################
admins: cyrus root
#################################
sendmail: /usr/sbin/sendmail
#################################
hashimapspool: true
fulldirhash: 1
altnamespace: yes
shimapspool: true
allowusermoves: 1
#################################
#sasl_pwcheck_method: saslauthd
#sasl_pwcheck_methodsasl_pwcheck_method: sasldb
sasl_pwcheck_method: saslauthd
sasl_auxprop_plugin: sasldb
sasl_mech_list: PLAIN LOGIN
unixhierarchysep: yes
sasl_saslauthd_path: /var/run/saslauthd/mux
#############################
autocreate_post: yes
autosubscribe_post: yes
autosubscribe_new_mailbox: yes
#############################
duplicatesuppression: 0
munge8bit: 0
allowplaintext: yes
proc_path: /run/cyrus/proc
mboxname_lockpath: /run/cyrus/lock
duplicate_db_path: /run/cyrus/db/deliver.db
ptscache_db_path:  /run/cyrus/db/ptscache.db
statuscache_db_path: /run/cyrus/db/statuscache.db
tls_sessions_db_path: /run/cyrus/db/tls_sessions.db
defaultpartition: default
lmtpsocket: /run/cyrus/socket/lmtp
idlesocket: /run/cyrus/socket/idle
notifysocket: /run/cyrus/socket/notify
syslog_prefix: cyrus
#################################################################
tls_server_cert: /etc/pki/tls/certs/mail.crt
tls_server_key: /etc/pki/tls/private/mail.key
loginmaxretries: 3
loginrealms: idle-r.ru
loginuseacl: yes
