# Режим работы
Mode                    sv

# Сокет (должен совпадать с настройкой в Postfix)
Socket                  inet:8891@127.0.0.1

# Параметры домена
Domain                  idle-r.ru
KeyFile                 /var/lib/opendkim/keys/idle-r.ru/mail.private
Selector                mail

# Алгоритм
SignatureAlgorithm      rsa-sha256

# Доверенные хосты
#InternalHosts           refile:/etc/opendkim/TrustedHosts

# Если есть строки KeyTable/SigningTable — закомментируйте их:
# KeyTable              /etc/opendkim/KeyTable
# SigningTable          refile:/etc/opendkim/SigningTable
InternalHosts           127.0.0.1, ::1,
